# Generated by Django 5.0.4 on 2024-04-29 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeBanners',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('media', models.OneToOneField(db_column='media_id', on_delete=django.db.models.deletion.RESTRICT, to='Master.medias')),
            ],
            options={
                'db_table': '"food_orders"."home_banners"',
            },
        ),
    ]
