# Generated by Django 5.0.4 on 2024-06-15 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupons',
            fields=[
                ('code', models.CharField(db_column='code', max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('end_date', models.BigIntegerField()),
                ('start_date', models.BigIntegerField()),
                ('quantity', models.IntegerField()),
                ('percentage', models.IntegerField()),
                ('max_discount_price', models.FloatField()),
                ('min_order_price', models.FloatField()),
                ('discount_price', models.FloatField()),
                ('is_fix', models.BooleanField()),
                ('expired', models.BooleanField()),
            ],
            options={
                'db_table': '"food_orders"."coupons"',
            },
        ),
        migrations.CreateModel(
            name='Promos',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('percentage', models.FloatField()),
                ('start_date', models.BigIntegerField()),
                ('end_date', models.BigIntegerField()),
            ],
            options={
                'db_table': '"food_orders"."promos"',
            },
        ),
        migrations.CreateModel(
            name='Menus',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(default='-')),
                ('price', models.FloatField()),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='menus', to='master.categories')),
                ('media_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='menus', to='master.medias')),
                ('promo_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='menus', to='order_transactions.promos')),
            ],
            options={
                'db_table': '"food_orders"."menus"',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('session', models.CharField(db_column='session', max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField()),
                ('queue', models.IntegerField()),
                ('total_price', models.FloatField()),
                ('final_price', models.FloatField()),
                ('order_date', models.DateTimeField()),
                ('payment_code', models.CharField(max_length=20)),
                ('payment', models.BooleanField()),
                ('coupon_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='orders', to='order_transactions.coupons')),
                ('payment_method_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='orders', to='master.paymentmethod')),
            ],
            options={
                'db_table': '"food_orders"."orders"',
            },
        ),
        migrations.CreateModel(
            name='OrderMenus',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('menu_id', models.ForeignKey(db_column='menu_id', on_delete=django.db.models.deletion.RESTRICT, related_name='order_menus', to='order_transactions.menus')),
                ('session', models.ForeignKey(db_column='session', on_delete=django.db.models.deletion.RESTRICT, related_name='order_menus', to='order_transactions.orders')),
            ],
            options={
                'db_table': '"food_orders"."order_menus"',
            },
        ),
    ]
