# Generated by Django 5.0.4 on 2024-05-09 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermenus',
            name='session',
            field=models.ForeignKey(db_column='session', on_delete=django.db.models.deletion.RESTRICT, related_name='order_transactions', to='order_transactions.orders'),
        ),
    ]
