# Generated by Django 5.0.4 on 2024-07-06 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_rename_media_id_homebanners_media'),
        ('order_transactions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menus',
            name='category_id',
        ),
        migrations.RemoveField(
            model_name='ordermenus',
            name='menu_id',
        ),
        migrations.RemoveField(
            model_name='ordermenus',
            name='session',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='payment_method_id',
        ),
        migrations.AddField(
            model_name='menus',
            name='category',
            field=models.ForeignKey(db_column='category_id', default='-', on_delete=django.db.models.deletion.RESTRICT, related_name='menus', to='master.categories'),
        ),
        migrations.AddField(
            model_name='ordermenus',
            name='menu',
            field=models.ForeignKey(db_column='menu_id', default='-', on_delete=django.db.models.deletion.RESTRICT, related_name='order_menus', to='order_transactions.menus'),
        ),
        migrations.AddField(
            model_name='ordermenus',
            name='order',
            field=models.ForeignKey(db_column='session', default='-', on_delete=django.db.models.deletion.RESTRICT, related_name='order_menus', to='order_transactions.orders'),
        ),
        migrations.AddField(
            model_name='orders',
            name='payment_method',
            field=models.ForeignKey(db_column='payment_method_id', default='-', on_delete=django.db.models.deletion.RESTRICT, related_name='orders', to='master.paymentmethod'),
        ),
    ]
