# Generated by Django 5.0.4 on 2024-07-06 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_transactions', '0002_remove_menus_category_id_remove_ordermenus_menu_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='coupon_code',
        ),
        migrations.AddField(
            model_name='orders',
            name='coupon',
            field=models.ForeignKey(db_column='coupon_code', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='orders', to='order_transactions.coupons'),
        ),
    ]
