# Generated by Django 5.0.4 on 2024-07-06 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homebanners',
            old_name='media_id',
            new_name='media',
        ),
    ]
