# Generated by Django 5.0.4 on 2024-05-11 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homebanners',
            name='media_id',
            field=models.OneToOneField(db_column='media_id', on_delete=django.db.models.deletion.RESTRICT, related_name='home_banners', to='master.medias'),
        ),
    ]
