# Message Response
SUCCESS_REGISTER = "Register success, check your email for account verification"
FAILED_REGISTER = "Register failed, please provide the correct data"
DESTINATION_NOT_VALID = "Destination is not valid"
WRONG_FORMAT_FILE = "Wrong format file, make sure it's a image format"
FILE_TOO_LARGE = "File too large, max size is {0} Mb"
SERVER_ERROR = "Something wrong with the server"
USED_USERNAME_EMAIL = "Username or email already used"
PASSWORD_NOT_SAME = "Password and confirmation password is not same"
WRONG_GENDER = "Wrong gender"
PATH_NOT_FOUND = "Path {0} not found"
BAD_REQUEST = "Bad request"
LOGIN_SUCCESS = "Success login"
LOGIN_ERROR = "Username/email or password is wrong"
SUCCESS_GET_LIST = "Success get list {0} with length {1}"
NOT_VERIFY = "Account not active, please verify your account first"
SUCCESS_RESEND_VERIFICATION = "Success resend verification, please check your email"
SUCCESS_SEND_FORGET_PASSWORD = "Success send forget password, please check your email"
EMAIL_NOT_EXIST = "Email is not register yet"
ACCOUNT_ALREADY_ACTIVATE = "Account is already activate"
NOT_VALID_TOKEN = "Token is not valid"
EXPIRED_VERIFICATION_TOKEN = "Token is expired"
VERIFY_ACCOUNT_SUCCESS = "Success verify your account, please login"
CHANGE_PASSWORD_SUCCESS = "Success change password, please login"
SUCCESS_CATEGORY = "Success add category"

# Email event
REGISTER = "REGISTER"
RESEND_VERIFY = "RESEND_VERIFY"
FORGET_PASSWORD = "FORGET_PASSWORD"

# Email
SUBJECT_VERIFICATION = "Pinara Account Verification"
BODY_ACCOUNT_VERIFICATION = "Halo {0}, silakan klik tombol di bawah untuk melakukan verifikasi akun sebelum {1}."
BODY_FORGET_PASSWORD = "Halo {0}, silakan klik tombol di bawah untuk melakukan reset password sebelum {1}."
