# Generated by Django 5.0.4 on 2024-05-09 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('username', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, null=True)),
                ('password', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('gender', models.CharField(choices=[('P', 'Pria'), ('W', 'Wanita')], max_length=1)),
                ('birth_date', models.DateField()),
                ('email', models.CharField(max_length=100, null=True, unique=True)),
                ('activate', models.BooleanField(default=False)),
            ],
            options={
                'db_table': '"food_orders"."users"',
            },
        ),
        migrations.CreateModel(
            name='ForgetPasswords',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=100, unique=True)),
                ('expired_at', models.DateTimeField()),
                ('username', models.OneToOneField(db_column='username', on_delete=django.db.models.deletion.RESTRICT, to='authentication.users')),
            ],
            options={
                'db_table': '"food_orders"."forget_passwords"',
            },
        ),
        migrations.CreateModel(
            name='UserVerifies',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=100, unique=True)),
                ('expired_at', models.DateTimeField()),
                ('username', models.OneToOneField(db_column='username', on_delete=django.db.models.deletion.RESTRICT, to='authentication.users')),
            ],
            options={
                'db_table': '"food_orders"."user_verifies"',
            },
        ),
    ]
