# Generated by Django 5.0.4 on 2024-07-06 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forgetpasswords',
            old_name='username',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='userverifies',
            old_name='username',
            new_name='user',
        ),
    ]
