# Generated by Django 5.0.4 on 2024-05-11 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forgetpasswords',
            name='username',
            field=models.OneToOneField(db_column='username', on_delete=django.db.models.deletion.RESTRICT, related_name='forget_passwords', to='authentication.users'),
        ),
        migrations.AlterField(
            model_name='userverifies',
            name='username',
            field=models.OneToOneField(db_column='username', on_delete=django.db.models.deletion.RESTRICT, related_name='user_verifies', to='authentication.users'),
        ),
    ]
