# Generated by Django 5.0.4 on 2024-05-09 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Couponts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('end_date', models.DateField(auto_now_add=True)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('quantity', models.IntegerField()),
                ('percentage', models.IntegerField()),
                ('max_discount_price', models.IntegerField()),
                ('min_order_price', models.IntegerField()),
                ('discount_price', models.IntegerField()),
                ('is_fix', models.BooleanField()),
                ('expired', models.BooleanField()),
            ],
            options={
                'db_table': '"food_orders"."couponts"',
            },
        ),
        migrations.CreateModel(
            name='Menus',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField()),
                ('price', models.IntegerField()),
                ('promo_price', models.IntegerField()),
                ('promo', models.BooleanField()),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master', to='master.categories')),
                ('media_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master', to='master.medias')),
                ('promo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master', to='master.promos')),
            ],
            options={
                'db_table': '"food_orders"."Menus"',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField()),
                ('name', models.CharField()),
                ('queue', models.IntegerField()),
                ('total_price', models.IntegerField()),
                ('final_price', models.IntegerField()),
                ('order_date', models.DateField()),
                ('payment_code', models.CharField(max_length=20)),
                ('payment', models.BooleanField()),
                ('coupont_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='order_transactions.couponts')),
                ('payment_method_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master', to='master.paymentmethod')),
            ],
            options={
                'db_table': '"food_orders"."orders"',
            },
        ),
        migrations.CreateModel(
            name='OrderMenus',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('menu_id', models.CharField()),
                ('quantity', models.IntegerField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_transactions', to='order_transactions.orders')),
            ],
            options={
                'db_table': '"food_orders"."order_menus"',
            },
        ),
    ]
